import Head from 'next/head'
import styles from '@/styles/Home.module.css'

type Products = {
  id: string, //number
  title: string
}

export default function Home(props: {products: Products[]}) {
  const {products} = props
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {products.map(mp => (<li key={mp.id}>{mp.title}</li>))}
        </ul>
      </main>
    </>
  )
}


export async function getStaticProps(): Promise<{props: {products:Products[]}}>{
  return {
    props: {
      products: [{ id:'p1', title:'Product 1'}],
    }
  }
}